# Generated by Django 3.2.5 on 2021-07-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_talent',
            field=models.BooleanField(default=True),
        ),
    ]
